[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
Q:
del D:GAME.OBJ
del D:GAME.EXE
echo === BC === > D:BUILD.LOG
BC D:GAME.BAS, D:GAME.OBJ, D:GAME.LST /O /W /E; >> D:BUILD.LOG
echo === LINK === >> D:BUILD.LOG
LINK D:GAME.OBJ, D:GAME.EXE, D:GAME.MAP, QB.LIB; >> D:BUILD.LOG
echo === DONE === >> D:BUILD.LOG
exit
