[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src\tools
Q:
del D:HAEDIT.OBJ
del D:HAEDIT.EXE
echo === BC === > D:HBUILD.LOG
BC D:HAEDIT.BAS, D:HAEDIT.OBJ, D:HAEDIT.LST /O; >> D:HBUILD.LOG
echo === LINK === >> D:HBUILD.LOG
LINK D:HAEDIT.OBJ, D:HAEDIT.EXE, D:HAEDIT.MAP, QB.LIB; >> D:HBUILD.LOG
echo === DONE === >> D:HBUILD.LOG
exit
