[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\HSCRTEST.OBJ
del D:\TOOLS\HSCRTEST.EXE
echo === BC === > D:\TOOLS\HSBUILD.LOG
BC D:\TOOLS\HSCRTEST.BAS, D:\TOOLS\HSCRTEST.OBJ, D:\TOOLS\HSCRTEST.LST /O; >> D:\TOOLS\HSBUILD.LOG
echo === LINK === >> D:\TOOLS\HSBUILD.LOG
LINK /SEG:800 D:\TOOLS\HSCRTEST.OBJ, D:\TOOLS\HSCRTEST.EXE, D:\TOOLS\HSCRTEST.MAP, QB.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\HSBUILD.LOG
echo === DONE === >> D:\TOOLS\HSBUILD.LOG
exit
