[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\PGDIAG.OBJ
del D:\TOOLS\PGDIAG.EXE
echo === BC === > D:\TOOLS\PGDBUILD.LOG
BC D:\TOOLS\PGDIAG.BAS, D:\TOOLS\PGDIAG.OBJ, D:\TOOLS\PGDIAG.LST /O; >> D:\TOOLS\PGDBUILD.LOG
echo === LINK === >> D:\TOOLS\PGDBUILD.LOG
LINK /SEG:800 D:\TOOLS\PGDIAG.OBJ, D:\TOOLS\PGDIAG.EXE, D:\TOOLS\PGDIAG.MAP, QB.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\PGDBUILD.LOG
echo === DONE === >> D:\TOOLS\PGDBUILD.LOG
exit
