[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\PGFLIP.OBJ
del D:\TOOLS\PGFLIP.EXE
echo === BC === > D:\TOOLS\PGBUILD.LOG
BC D:\TOOLS\PGFLIP.BAS, D:\TOOLS\PGFLIP.OBJ, D:\TOOLS\PGFLIP.LST /O; >> D:\TOOLS\PGBUILD.LOG
echo === LINK === >> D:\TOOLS\PGBUILD.LOG
LINK /SEG:800 D:\TOOLS\PGFLIP.OBJ, D:\TOOLS\PGFLIP.EXE, D:\TOOLS\PGFLIP.MAP, QB.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\PGBUILD.LOG
echo === DONE === >> D:\TOOLS\PGBUILD.LOG
exit
