[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\SCRLT2.OBJ
del D:\TOOLS\SCRLT2.EXE
echo === BC === > D:\TOOLS\S2BUILD.LOG
BC D:\TOOLS\SCRLT2.BAS, D:\TOOLS\SCRLT2.OBJ, D:\TOOLS\SCRLT2.LST /O; >> D:\TOOLS\S2BUILD.LOG
echo === LINK === >> D:\TOOLS\S2BUILD.LOG
LINK /SEG:800 D:\TOOLS\SCRLT2.OBJ, D:\TOOLS\SCRLT2.EXE, D:\TOOLS\SCRLT2.MAP, QB.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\S2BUILD.LOG
echo === DONE === >> D:\TOOLS\S2BUILD.LOG
exit
