[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\SCRLTEST.OBJ
del D:\TOOLS\SCRLTEST.EXE
echo === BC === > D:\TOOLS\STBUILD.LOG
BC D:\TOOLS\SCRLTEST.BAS, D:\TOOLS\SCRLTEST.OBJ, D:\TOOLS\SCRLTEST.LST /O; >> D:\TOOLS\STBUILD.LOG
echo === LINK === >> D:\TOOLS\STBUILD.LOG
LINK /SEG:800 D:\TOOLS\SCRLTEST.OBJ, D:\TOOLS\SCRLTEST.EXE, D:\TOOLS\SCRLTEST.MAP, QB.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\STBUILD.LOG
echo === DONE === >> D:\TOOLS\STBUILD.LOG
exit
