[sdl]
autolock=false

[cpu]
cycles=max

[autoexec]
mount Q C:\Code\TOOLS\qb45
mount D C:\Code\Dark-Visions\src
set INCLUDE=D:\UGL
Q:
del D:\TOOLS\UGLTEST.OBJ
del D:\TOOLS\UGLTEST.EXE
echo === BC === > D:\TOOLS\UTBUILD.LOG
BC D:\TOOLS\UGLTEST.BAS, D:\TOOLS\UGLTEST.OBJ, D:\TOOLS\UGLTEST.LST /O; >> D:\TOOLS\UTBUILD.LOG
echo === LINK === >> D:\TOOLS\UTBUILD.LOG
LINK /SEG:800 D:\TOOLS\UGLTEST.OBJ, D:\TOOLS\UGLTEST.EXE, D:\TOOLS\UGLTEST.MAP, BCOM45.LIB+D:\UGL\UGL.LIB; >> D:\TOOLS\UTBUILD.LOG
echo === DONE === >> D:\TOOLS\UTBUILD.LOG
exit
